services:
  db:
    build: ./postgres-andthen/
    restart: always
    environment:
      POSTGRES_USER: andthen_super
      POSTGRES_PASSWORD: temporary_password
    ports:
      - 5432:5432

  auth:
    image: andthen-auth
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://andthen_auth:temporary_password@db:5432/andthen

  gateway:
    build: ./gateway-andthen/
    restart: always
    depends_on:
      - players
      - games
      - auth
    ports:
      - 80:80

  players:
    image: andthen-players
    restart: always
    depends_on:
      - db
    environment:
      PGUSER: andthen_players
      PGHOST: db
      PGPASSWORD: temporary_password
      PGDATABASE: andthen

  games:
    image: andthen-games
    restart: always
    depends_on:
      - db
    environment:
      PGUSER: andthen_games
      PGHOST: db
      PGPASSWORD: temporary_password
      PGDATABASE: andthen
